{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
      - name: {{ .Values.appLabel }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        env:
        {{- if .Values.appname_enabled }}
        - name: SPRING_APPLICATION_NAME
          value: {{ .Values.appName }}
        {{- end }}
        {{- if .Values.profile_enabled }}
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_PROFILES_ACTIVE
        {{- end }}
        {{- if .Values.git_enabled }}
        - name: GIT_URI
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: GIT_URI
        {{- end }}
        {{- if .Values.config_enabled }}
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: CONFIGSERVER_URL
        {{- end }}
        {{- if .Values.eureka_enabled }}
        - name: EUREKA_HOST
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: EUREKA_HOST
        {{- end }}
        {{- if .Values.resouceserver_enabled }}
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
        {{- end }}
        {{- if .Values.keycloak_enabled }}
        - name: NEXT_GEN_UAMS_CLIENT_SECRET
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: NEXT_GEN_UAMS_CLIENT_SECRET
        - name: KEYCLOACK_TOKEN_URL
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KEYCLOACK_TOKEN_URL
        - name: KEYCLOACK_USER_URL
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KEYCLOACK_USER_URL
        {{- end }}
        {{- if .Values.mysql_uams_enabled }}
        - name: UAMS_DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: UAMS_DB_HOST
        - name: UAMS_DB_USER
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: UAMS_DB_USER
        - name: UAMS_DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-auth
              key: mysql-password
        {{- end }}
        {{- if .Values.mysql_accounts_enabled }}
        - name: NEXT_GEN_ACCOUNTS_DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: NEXT_GEN_ACCOUNTS_DB_HOST
        - name: NEXT_GEN_ACCOUNTS_DB_USER
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: NEXT_GEN_ACCOUNTS_DB_USER
        - name: NEXT_GEN_ACCOUNTS_DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-auth
              key: mysql-password
        {{- end }}
        {{- if .Values.otel_enabled }}
        - name: JAVA_TOOL_OPTIONS
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: JAVA_TOOL_OPTIONS
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_METRICS_EXPORTER
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: OTEL_METRICS_EXPORTER
        - name: OTEL_LOGS_EXPORTER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: OTEL_LOGS_EXPORTER
        - name: OTEL_SERVICE_NAME
          value: {{ .Values.appName }}
        {{- end }}
        {{- if .Values.kafka_enabled }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KAFKA_BOOTSTRAP_SERVERS
        {{- end }}
        
{{- end -}}