apiVersion: v2
name: keycloak
description: A Helm chart for deploying Keycloak with PostgreSQL
type: application
version: 0.1.0
appVersion: "22.0.1"

dependencies:
  - name: keycloak
    version: 19.0.0
    repository: https://charts.bitnami.com/bitnami
