apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
type: Opaque
data:
  mysql-root-password: bmV4dGdlbnJvb3RAMTIz
  mysql-password: bmV4dGdlbkAxMjM= # If using user authentication
  nextgen-uams-client-secret: akdGcmdOcWJTWXJsR3I5ZmtOR0JPendkMG1yWjgxNGI= # Base64 encoded client secret

